/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module synth_top(clk, rst_n, s_axis_tdata, s_axis_tvalid, s_axis_tlast, s_axis_tready, m_axis_tdata, m_axis_tvalid, m_axis_tlast, m_axis_tready, cfg_d, cfg_t, precision, start, done);
  wire _000_;
  wire [63:0] _001_;
  wire [63:0] _002_;
  wire [63:0] _003_;
  wire _004_;
  wire _005_;
  wire [15:0] _006_;
  wire [23:0] _007_;
  wire [8:0] _008_;
  wire [9:0] _009_;
  wire [10:0] _010_;
  wire [23:0] _011_;
  wire [23:0] _012_;
  wire [23:0] _013_;
  wire [23:0] _014_;
  wire [23:0] _015_;
  wire [23:0] _016_;
  wire [23:0] _017_;
  wire [23:0] _018_;
  wire [23:0] _019_;
  wire [23:0] _020_;
  wire [23:0] _021_;
  wire [23:0] _022_;
  wire [23:0] _023_;
  wire [23:0] _024_;
  wire [23:0] _025_;
  wire [23:0] _026_;
  wire [23:0] _027_;
  wire [23:0] _028_;
  wire [23:0] _029_;
  wire [23:0] _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire [15:0] _043_;
  wire [15:0] _044_;
  wire [2:0] _045_;
  wire [2:0] _046_;
  wire [2:0] _047_;
  wire [2:0] _048_;
  wire [2:0] _049_;
  wire [2:0] _050_;
  wire [2:0] _051_;
  wire [2:0] _052_;
  wire [23:0] _053_;
  wire [14:0] beat_sum;
  wire [7:0] byte0;
  wire [7:0] byte1;
  wire [7:0] byte2;
  wire [7:0] byte3;
  wire [7:0] byte4;
  wire [7:0] byte5;
  wire [7:0] byte6;
  wire [7:0] byte7;
  input [7:0] cfg_d;
  input [7:0] cfg_t;
  input clk;
  output done;
  reg done;
  wire [7:0] eb0;
  wire [7:0] eb1;
  wire [7:0] eb2;
  wire [7:0] eb3;
  wire [7:0] eb4;
  wire [7:0] eb5;
  wire [7:0] eb6;
  wire [7:0] eb7;
  wire [63:0] exp_beat;
  output [63:0] m_axis_tdata;
  output m_axis_tlast;
  input m_axis_tready;
  output m_axis_tvalid;
  wire [63:0] norm_beat;
  reg [63:0] \pipe_data[0] ;
  reg [63:0] \pipe_data[1] ;
  reg [63:0] \pipe_data[2] ;
  reg [63:0] \pipe_data[3] ;
  reg [63:0] \pipe_data[4] ;
  reg [63:0] \pipe_data[5] ;
  reg [63:0] \pipe_data[6] ;
  reg [63:0] \pipe_data[7] ;
  reg \pipe_last[0] ;
  reg \pipe_last[1] ;
  reg \pipe_last[2] ;
  reg \pipe_last[3] ;
  reg \pipe_last[4] ;
  reg \pipe_last[5] ;
  reg \pipe_last[6] ;
  reg \pipe_last[7] ;
  reg \pipe_valid[0] ;
  reg \pipe_valid[1] ;
  reg \pipe_valid[2] ;
  reg \pipe_valid[3] ;
  reg \pipe_valid[4] ;
  reg \pipe_valid[5] ;
  reg \pipe_valid[6] ;
  reg \pipe_valid[7] ;
  input precision;
  input rst_n;
  reg [15:0] running_max;
  reg [23:0] running_sum;
  input [63:0] s_axis_tdata;
  input s_axis_tlast;
  output s_axis_tready;
  input s_axis_tvalid;
  input start;
  assign _008_ = \pipe_data[2] [7:0] + \pipe_data[2] [15:8];
  assign _009_ = _008_ + \pipe_data[2] [23:16];
  assign _010_ = _009_ + \pipe_data[2] [31:24];
  assign _011_[11:0] = _010_ + \pipe_data[2] [39:32];
  assign _012_[12:0] = _011_[11:0] + \pipe_data[2] [47:40];
  assign _013_[13:0] = _012_[12:0] + \pipe_data[2] [55:48];
  assign beat_sum = _013_[13:0] + \pipe_data[2] [63:56];
  assign _014_ = running_sum + beat_sum;
  assign _000_ = \pipe_valid[7]  & \pipe_last[7] ;
  assign _023_ = { 8'h00, _015_[15:0] } / running_sum;
  assign _024_ = { 8'h00, _016_[15:0] } / running_sum;
  assign _025_ = { 8'h00, _017_[15:0] } / running_sum;
  assign _026_ = { 8'h00, _018_[15:0] } / running_sum;
  assign _027_ = { 8'h00, _019_[15:0] } / running_sum;
  assign _028_ = { 8'h00, _020_[15:0] } / running_sum;
  assign _029_ = { 8'h00, _021_[15:0] } / running_sum;
  assign _030_ = { 8'h00, _022_[15:0] } / running_sum;
  assign _031_ = $signed({ 1'h0, \pipe_data[0] [7:0] }) > $signed(running_max);
  assign _032_ = running_max[2:0] > \pipe_data[1] [2:0];
  assign _033_ = running_max[2:0] > \pipe_data[1] [10:8];
  assign _034_ = running_max[2:0] > \pipe_data[1] [18:16];
  assign _035_ = running_max[2:0] > \pipe_data[1] [26:24];
  assign _036_ = running_max[2:0] > \pipe_data[1] [34:32];
  assign _037_ = running_max[2:0] > \pipe_data[1] [42:40];
  assign _038_ = running_max[2:0] > \pipe_data[1] [50:48];
  assign _039_ = running_max[2:0] > \pipe_data[1] [58:56];
  assign _040_ = s_axis_tvalid && s_axis_tready;
  assign _015_[15:0] = \pipe_data[3] [7:0] * 8'hff;
  assign _016_[15:0] = \pipe_data[3] [15:8] * 8'hff;
  assign _017_[15:0] = \pipe_data[3] [23:16] * 8'hff;
  assign _018_[15:0] = \pipe_data[3] [31:24] * 8'hff;
  assign _019_[15:0] = \pipe_data[3] [39:32] * 8'hff;
  assign _020_[15:0] = \pipe_data[3] [47:40] * 8'hff;
  assign _021_[15:0] = \pipe_data[3] [55:48] * 8'hff;
  assign _022_[15:0] = \pipe_data[3] [63:56] * 8'hff;
  assign _041_ = | running_sum;
  assign _042_ = ~ \pipe_valid[0] ;
  assign s_axis_tready = m_axis_tready | _042_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      done <= 1'h0;
    else
      done <= _000_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_data[7]  <= 64'h0000000000000000;
    else
      \pipe_data[7]  <= \pipe_data[6] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_valid[7]  <= 1'h0;
    else
      \pipe_valid[7]  <= \pipe_valid[6] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_last[7]  <= 1'h0;
    else
      \pipe_last[7]  <= \pipe_last[6] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_data[6]  <= 64'h0000000000000000;
    else
      \pipe_data[6]  <= \pipe_data[5] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_valid[6]  <= 1'h0;
    else
      \pipe_valid[6]  <= \pipe_valid[5] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_last[6]  <= 1'h0;
    else
      \pipe_last[6]  <= \pipe_last[5] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_data[5]  <= 64'h0000000000000000;
    else
      \pipe_data[5]  <= \pipe_data[4] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_valid[5]  <= 1'h0;
    else
      \pipe_valid[5]  <= \pipe_valid[4] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_last[5]  <= 1'h0;
    else
      \pipe_last[5]  <= \pipe_last[4] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_data[4]  <= 64'h0000000000000000;
    else
      \pipe_data[4]  <= _003_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_valid[4]  <= 1'h0;
    else
      \pipe_valid[4]  <= \pipe_valid[3] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_last[4]  <= 1'h0;
    else
      \pipe_last[4]  <= \pipe_last[3] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      running_sum <= 24'h000000;
    else
      running_sum <= _007_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_data[3]  <= 64'h0000000000000000;
    else
      \pipe_data[3]  <= \pipe_data[2] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_valid[3]  <= 1'h0;
    else
      \pipe_valid[3]  <= \pipe_valid[2] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_last[3]  <= 1'h0;
    else
      \pipe_last[3]  <= \pipe_last[2] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_data[2]  <= 64'h0000000000000000;
    else
      \pipe_data[2]  <= _002_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_valid[2]  <= 1'h0;
    else
      \pipe_valid[2]  <= \pipe_valid[1] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_last[2]  <= 1'h0;
    else
      \pipe_last[2]  <= \pipe_last[1] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      running_max <= 16'h8000;
    else
      running_max <= _006_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_data[1]  <= 64'h0000000000000000;
    else
      \pipe_data[1]  <= \pipe_data[0] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_valid[1]  <= 1'h0;
    else
      \pipe_valid[1]  <= \pipe_valid[0] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_last[1]  <= 1'h0;
    else
      \pipe_last[1]  <= \pipe_last[0] ;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_data[0]  <= 64'h0000000000000000;
    else
      \pipe_data[0]  <= _001_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_valid[0]  <= 1'h0;
    else
      \pipe_valid[0]  <= _005_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      \pipe_last[0]  <= 1'h0;
    else
      \pipe_last[0]  <= _004_;
  assign _007_ = \pipe_valid[2]  ? _053_ : running_sum;
  assign _043_ = _031_ ? { 8'h00, \pipe_data[0] [7:0] } : running_max;
  assign _044_ = \pipe_last[0]  ? 16'h8000 : _043_;
  assign _006_ = \pipe_valid[0]  ? _044_ : running_max;
  assign _004_ = _040_ ? s_axis_tlast : \pipe_last[0] ;
  assign _005_ = _040_ ? 1'h1 : 1'h0;
  assign _001_ = _040_ ? s_axis_tdata : \pipe_data[0] ;
  assign _045_ = _032_ ? 3'h7 : 3'h0;
  assign _046_ = _033_ ? 3'h7 : 3'h0;
  assign _047_ = _034_ ? 3'h7 : 3'h0;
  assign _048_ = _035_ ? 3'h7 : 3'h0;
  assign _049_ = _036_ ? 3'h7 : 3'h0;
  assign _050_ = _037_ ? 3'h7 : 3'h0;
  assign _051_ = _038_ ? 3'h7 : 3'h0;
  assign _052_ = _039_ ? 3'h7 : 3'h0;
  assign _002_ = \pipe_valid[1]  ? exp_beat : \pipe_data[1] ;
  assign _053_ = \pipe_last[2]  ? 24'h000000 : _014_;
  assign norm_beat[7:0] = _041_ ? _023_[7:0] : 8'h00;
  assign norm_beat[15:8] = _041_ ? _024_[7:0] : 8'h00;
  assign norm_beat[23:16] = _041_ ? _025_[7:0] : 8'h00;
  assign norm_beat[31:24] = _041_ ? _026_[7:0] : 8'h00;
  assign norm_beat[39:32] = _041_ ? _027_[7:0] : 8'h00;
  assign norm_beat[47:40] = _041_ ? _028_[7:0] : 8'h00;
  assign norm_beat[55:48] = _041_ ? _029_[7:0] : 8'h00;
  assign norm_beat[63:56] = _041_ ? _030_[7:0] : 8'h00;
  assign _003_ = \pipe_valid[3]  ? norm_beat : \pipe_data[3] ;
  reg [7:0] exp_lut [7:0];
  initial begin
    exp_lut[0] = 8'hff;
    exp_lut[1] = 8'he0;
    exp_lut[2] = 8'hc5;
    exp_lut[3] = 8'hae;
    exp_lut[4] = 8'h99;
    exp_lut[5] = 8'h87;
    exp_lut[6] = 8'h77;
    exp_lut[7] = 8'h69;
  end
  assign exp_beat[7:0] = exp_lut[_045_];
  assign exp_beat[15:8] = exp_lut[_046_];
  assign exp_beat[23:16] = exp_lut[_047_];
  assign exp_beat[31:24] = exp_lut[_048_];
  assign exp_beat[39:32] = exp_lut[_049_];
  assign exp_beat[47:40] = exp_lut[_050_];
  assign exp_beat[55:48] = exp_lut[_051_];
  assign exp_beat[63:56] = exp_lut[_052_];
  assign _011_[23:12] = 12'h000;
  assign _012_[23:13] = 11'h000;
  assign _013_[23:14] = 10'h000;
  assign _015_[23:16] = 8'h00;
  assign _016_[23:16] = 8'h00;
  assign _017_[23:16] = 8'h00;
  assign _018_[23:16] = 8'h00;
  assign _019_[23:16] = 8'h00;
  assign _020_[23:16] = 8'h00;
  assign _021_[23:16] = 8'h00;
  assign _022_[23:16] = 8'h00;
  assign byte0 = \pipe_data[1] [7:0];
  assign byte1 = \pipe_data[1] [15:8];
  assign byte2 = \pipe_data[1] [23:16];
  assign byte3 = \pipe_data[1] [31:24];
  assign byte4 = \pipe_data[1] [39:32];
  assign byte5 = \pipe_data[1] [47:40];
  assign byte6 = \pipe_data[1] [55:48];
  assign byte7 = \pipe_data[1] [63:56];
  assign eb0 = \pipe_data[3] [7:0];
  assign eb1 = \pipe_data[3] [15:8];
  assign eb2 = \pipe_data[3] [23:16];
  assign eb3 = \pipe_data[3] [31:24];
  assign eb4 = \pipe_data[3] [39:32];
  assign eb5 = \pipe_data[3] [47:40];
  assign eb6 = \pipe_data[3] [55:48];
  assign eb7 = \pipe_data[3] [63:56];
  assign m_axis_tdata = \pipe_data[7] ;
  assign m_axis_tlast = \pipe_last[7] ;
  assign m_axis_tvalid = \pipe_valid[7] ;
endmodule
