// mac_llm_A.v
// Generated by: Claude Sonnet 4.6
// Prompt: synthesizable SystemVerilog MAC unit per ECE 410/510 Codefest 4 spec
 
module mac (
    input  clk,
    input  rst,
    input  [7:0] a,
    input  [7:0] b,
    output reg [31:0] out
);
 
    wire [15:0] product;
    assign product = a * b;  // BUG 1: unsigned multiply; no signed cast
 
    always @(posedge clk) begin  // BUG 2: plain always instead of always_ff
        if (rst)
            out <= 32'b0;
        else
            out <= out + {{16{product[15]}}, product};  // BUG 3: sign-extends an
                                                        // already-unsigned product
    end
 
endmodule