// mac_llm_B.v
// Generated by: GPT-4o
// Prompt: synthesizable SystemVerilog MAC unit per ECE 410/510 Codefest 4 spec

module mac (
    input  logic               clk,
    input  logic               rst,   // active-high synchronous reset
    input  logic signed [7:0]  a,
    input  logic signed [7:0]  b,
    output logic signed [31:0] out
);

    always_ff @(posedge clk) begin
        if (rst)
            out <= 32'sd0;
        else
            out <= out + (a * b);
    end

endmodule
