SIM            = icarus
TOPLEVEL_LANG  = verilog
VERILOG_SOURCES = $(PWD)/fused_norm_core.sv
TOPLEVEL       = fused_norm_core
MODULE         = fused_norm_core_tb
COMPILE_ARGS   += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
