SIM            = icarus
TOPLEVEL_LANG  = verilog
VERILOG_SOURCES = /content/mac_correct.v
TOPLEVEL       = mac
MODULE         = test_mac
COMPILE_ARGS   += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
